### ISSUE TITLE
MySQL Support for Institutions and Users

### ISSUE THREAD

**Issue by misilot** [zemkat/grima#12]
Is it possible to use mysql instead of the sqlite database?

**Comment by zemkat** [comment]
Yes! We use [PDO](https://www.php.net/manual/en/ref.pdo-mysql.connection.php) for the database connection, which supports SQLite, MySQL, postgres, SQL server, etc.  

To use MySQL, create the database with commands like:

```mysql
create database Grima_2020;
use Grima_2020;
grant all on Grima_2020.* to 'grimauser'@'localhost' identified by 'grimapass';
```

Then add to .htaccess:
```htaccess
setenv DATABASE_URL mysql:host=localhost;dbname=Grima_2020
setenv DATABASE_USER grimauser
setenv DATABASE_PASS grimapass
```

Here are some [example configs](https://public-grima.zemkat.org/docs/cloud/) for various databases.

**Comment by misilot** [comment]
Thank you for this, I hadn't come across the example configs page.
